### PR TITLE
request: dont throw when hooks is a string

### PR DESCRIPTION
**Pull request by yields**
cc @calvinfo

### CODE REVIEW

**Comment by yields** [comment]
not sure how we have `.hooks = ""` in our database :/

**Comment by f2prateek** [comment]
When is hooks ever a string? Not throwing makes sense, but I think we should surface an error, no?

**Comment by yields** [comment]
yeah, it shouldn't be i think, but still getting `"" has no method .filter()` (see team-infra for more info)

**Comment by calvinfo** [comment]
I think there's a bug in our validation logic somewhere in the site. 

@yields any reason you closed this? We should also fix it internally.

**Comment by f2prateek** [comment]
for anyone else following along - @yields discovered that metadata for web hooks provides "" as a default instead of [] which is most likely causing this issue.

**Comment by calvinfo** [comment]
Ahhh, good find guys.

**Pull request merged**
